apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: everything-java-
spec:
  pipelineRef:
    name: everything-java
  params:
  - name: appRepoUrl
    value: ssh://gitea@gitea.tssc.rht-set.com:2022/ploigos-reference-applications/reference-quarkus-mvn.git
  - name: appRepoRef
    value: main
  - name: devGitRefPatterns
    value: main
  - name: verbose
    value: 'true'
  workspaces:
  - name: app
    persistentVolumeClaim:
      claimName: app
  - name: home
    persistentVolumeClaim:
      claimName: home
  - name: maven-settings
    secret:
      secretName: maven-settings
  - name: sonar-settings
    secret:
      secretName: sonar-settings
