apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: create-container-image-
spec:
  taskRef:
    name: create-container-image
  params:
    - name: outputImageTag
      value: quay.io/dwinchell_redhat/my-image:latest
    - name: pauseForDebugBeforeStepRun
      value: "false"
    - name: verbose
      value: "true"
  workspaces:
    - name: home
      persistentVolumeClaim:
        claimName: home
    - name: app
      persistentVolumeClaim:
        claimName: app
    - name: container-auth
      secret:
        secretName: container-auth
