apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: pre-push-application-to-repository-
spec:
  taskRef:
    name: maven
  params:
    - name: GOALS
      value:
        - --no-transfer-progress
        - -DnewVersion=$(tasks.setup-generate-artifact-version.results.artifactVersion)
        - versions:set
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: app
    - name: maven-settings
      secret:
        secretName: maven-settings
