apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: push-application-to-repository-
spec:
  taskRef:
    name: maven
  params:
    - name: GOALS
      value:
        - --no-transfer-progress
        - -Dmaven.install.skip=true
        - -Dmaven.test.skip=true
        - -DskipTests
        - -DskipITs
        - -Dquarkus.build.skip=true
        - deploy
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: app
    - name: maven-settings
      secret:
        secretName: maven-settings
