---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-metadata-artifact-version
spec:
  params:
  - name: codeVersion
    type: string
  - name: gitRef
    type: string
  - name: gitCommit
    type: string
  - name: image
    type: string
    description: |
      Container image to run the steps of this task in.
    default: ubi8-minimal
  - name: imagePullPolicy
    type: string
    description: |
      Policy for pulling new versions of the given image.
    default: IfNotPresent
  results:
  - name: artifactVersion
    description: |
      A version string to use for the artifact created by this pipeline. Based on the source code version, git branch/tag, and git commit.
  steps:
  - name: generate-new-version
    image: $(params.image)
    imagePullPolicy: $(params.imagePullPolicy)
    script: |
      #!/bin/sh
      HASH_PREFIX=`echo -n "$(params.gitCommit)" | cut -c -5`
      NEW_VERSION="$(params.codeVersion)-$(params.gitRef)-${HASH_PREFIX}"
      echo "${NEW_VERSION}"
      echo -n "${NEW_VERSION}" > $(results.artifactVersion.path)
