---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openscap
spec:
  params:
  - name: containerImageTag
    type: string
    description: |
      The image to scan
  - name: image
    type: string
    description: |
      Container image to run the steps of this task in.
    default: quay.io/ploigos/ploigos-tool-openscap:v1.0.0
  - name: imagePullPolicy
    type: string
    description: |
      Policy for pulling new versions of the given image.
    default: IfNotPresent
  workspaces:
    - name: app
      description: The application source code
  steps:
  - name: read-code-version
    image: $(params.image)
    imagePullPolicy: $(params.imagePullPolicy)
    script: |
      #!/bin/sh
      echo -en \"Pulling image $(params.containerImageTag)\n\n\";
      buildah from --storage-driver vfs --log-level debug docker://$(params.containerImageTag);
      container_id=`buildah --storage-driver vfs containers -q`;
      buildah mount --storage-driver vfs $container_id;
      echo -en \"\nRunning oscap-chroot scan\n\";
      oscap-chroot $(buildah --storage-driver vfs mount | awk '{print $2}') oval eval --report /tmp/report.html /usr/share/xml/scap/ssg/content/ssg-jre-oval.xml
      cat /tmp/report.html
