---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: read-code-version-maven
spec:
  params:
  - name: pomPath
    type: string
    description: |
      The path to the Maven pom file (usually pom.xml) that has contains the version, relative to the root of the
      application source code.
    default: pom.xml
  - name: image
    type: string
    description: |
      Container image to run the steps of this task in.
    default: quay.io/dwinchell_redhat/ploigos-yq
  - name: imagePullPolicy
    type: string
    description: |
      Policy for pulling new versions of the given image.
    default: IfNotPresent
  results:
  - name: codeVersion
    description: |
      The version of the code, read from the source code itself.
  workspaces:
    - name: app
      description: The application source code, which must include a pom.xml file that has a version element.
  steps:
  - name: read-code-version
    image: $(params.image)
    imagePullPolicy: $(params.imagePullPolicy)
    script: |
      #!/bin/sh
      set -e
      POM_FILE=$(workspaces.app.path)/$(params.pomPath)
      VERSION=`yq e '.project.version' ${POM_FILE} -p xml`
      echo Version: ${VERSION}
      echo -n ${VERSION} > $(results.codeVersion.path)
